import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from '@/components/ui/Toast';
import { ReactQueryProvider } from "@/components/ReactQueryProvider"; // import the new provider

export const metadata: Metadata = {
  title: "Alora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ToastProvider>
        {children}
          </ToastProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
